plugins {
    id 'com.android.library'
}

android {
    namespace 'io.github.tommygeenexus.exifinterfaceextended'
    compileSdk 34

    defaultConfig {
        minSdk 14

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {

    implementation("androidx.annotation:annotation:1.8.0")
    implementation 'com.android.support:appcompat-v7:25.0.0'
    implementation project(':fotolib2')
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}